language: android
jdk: oraclejdk7

android:
  components:
  - build-tools-20.0.0

before_script:
- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

deploy:
  provider: releases
  api_key:
    secure: pdAe29uxa8bl5JPvt96MqvXtXCUQEUJPb+TAQbYUQeIIOdkvh6NPiv7py3h1exiwBzxJIw2QzW/f7ozmAPH21DIFF3XAgWcJnCbKv7ebGvslF1jgthubNyUa29nvJ+myBpfylTvWGk9GYEuz6RNFsKAOxo3oItdeuzz4dzqzibk=
  file: ./app/build/outputs/apk/app-release-unsigned.apk
  on:
    repo: outlying/njumeter
    branch: master
